name: Auto commit

on:
  push:
    branches:
      - master
  workflow_dispatch: # 手动触发
  schedule:
    - cron: "0 */2 * * *" # 每两小时检查一次

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
        
      - name: Generate Random Delay
        id: delay
        run: |
          # 生成一个 2 到 5 小时（7200 到 18000 秒）之间的随机延迟时间
          RANDOM_DELAY=$((7200 + RANDOM % 10800))
          echo "Random delay: $RANDOM_DELAY seconds"
          echo "::set-output name=delay::$RANDOM_DELAY"
        
      - name: Delay Job
        run: |
          echo "Waiting for ${{ steps.delay.outputs.delay }} seconds..."
          sleep ${{ steps.delay.outputs.delay }}

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "LoserLiunian@gmail.com"
          git config --local user.name "LoserLiunian"
          git add -A
          
          arr[0]="chore(bot): 😂 auto commit"
          arr[1]="chore(bot): 😱 auto commit"
          arr[2]="chore(bot): 👿 auto commit"
          arr[3]="chore(bot): 💩 auto commit"
          arr[4]="chore(bot): 🙏 auto commit"
          arr[5]="chore(bot): 🙈 auto commit"
          arr[6]="chore(bot): 🐐 auto commit"
          arr[7]="chore(bot): 🤖 auto commit"
          arr[8]="chore(bot): 🟩 auto commit"
          arr[9]="chore(bot): 👻 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
